application: example-project-13

version: test-frontend
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Route handlers
- url: /favicon\.ico
  static_files: ../favicon.ico
  upload: favicon\.ico

- url: /
  static_files: static/index.html
  upload: index\.html
  secure: always
  
- url: /api/oauth
  script: manejador_pb.app
  secure: always

- url: /api/.*
  script: manejador_pb.app
  
- url: /about
  static_files: static/index.html
  upload: index\.html
  
- url: /privacy
  static_files: static/index.html
  upload: index\.html
  secure: always

  
- url: /contact
  static_files: static/index.html
  upload: index\.html
  secure: always

- url: /selectId
  static_files: static/index.html
  upload: index\.html
  secure: always

- url: /user/.*
  static_files: static/index.html
  upload: index\.html
  secure: always
  
- url: /
  static_dir: static 
  secure: always
  

libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest
- name: pycrypto
  version: latest
