application: example-project-13
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Route handlers
- url: /favicon\.ico
  static_files: ../favicon.ico
  upload: favicon\.ico
- url: /app
  static_dir: ../static 
- url: .*
  script: manejador_pb.app

libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest